/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Created: Tue Mar 22 14:59:33 2022
*/

import * as THREE from "three";
import React, { useRef, useEffect } from "react";
import { useGLTF, PerspectiveCamera, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ART: THREE.Mesh;
    Brackets: THREE.Mesh;
    XR: THREE.Mesh;
  };
  materials: {
    ["Black Chrome"]: THREE.MeshStandardMaterial;
    Chrome: THREE.MeshStandardMaterial;
  };
};

type ActionName = "BracketsAction" | "Rotating LightsAction";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Logo(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "./models/ARTXR_Loader.glb"
  ) as GLTFResult;
  const { actions } = useAnimations<GLTFActions>(animations, group);
  // DEBUG
  console.log("Anims = ", actions);

  useEffect(() => {
    if (actions) {
      actions.BracketsAction.play();
      actions["Rotating LightsAction"].play();
    }
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="ART"
          castShadow
          receiveShadow
          geometry={nodes.ART.geometry}
          material={materials["Black Chrome"]}
        />
        <mesh
          name="Brackets"
          castShadow
          receiveShadow
          geometry={nodes.Brackets.geometry}
          material={materials.Chrome}
          position={[0.361, 0.01, 0]}
        />
        <mesh
          name="XR"
          castShadow
          receiveShadow
          geometry={nodes.XR.geometry}
          material={materials["Black Chrome"]}
        />
        <group name="Rotating_Lights">
          <group name="Blue" position={[1.54, -0.222, 0.217]}>
            <pointLight
              name="Blue_Orientation"
              intensity={500}
              decay={2}
              distance={2}
              color="#2c00ff"
              position={[0, 0, 0.5]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="Green" position={[1.5, -0.085, 0.2]} scale={1.111}>
            <pointLight
              name="Green_Orientation"
              intensity={500}
              decay={2}
              distance={2}
              color="#27ff00"
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="Red" position={[1.454, -0.003, -0.249]}>
            <pointLight
              name="Red_Orientation"
              intensity={500}
              decay={2}
              distance={2}
              color="#ff0000"
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group name="White" position={[-1.5, 0, 0]}>
            <pointLight
              name="White_Orientation"
              intensity={500}
              decay={2}
              distance={2}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/ARTXR_Loader.glb");
